### ISSUE TITLE
yiisoft 那个队列半成品 的沟在哪里？

### ISSUE THREAD

**Issue by fancyecommerce** [xutl/yii2-message#3]
之前看yiisoft上那个队列半成品给我带到沟里了，且它自带的redis的一直有bug,常年不维护。

你说的是：https://github.com/yiisoft/yii2-queue ？这个吗？

沟在哪里？

人家在维护呢、？https://github.com/yiisoft/yii2-queue/commits/master

**Comment by xutl** [comment]
我开发这个的时候，YII 那个还是半成品
